recipe_name: "fede_abril_preperfilamiento"
version: "1.0"
description: "Recipe for analyzing lead engagement in the active Fede Abril Re-engagement campaign, using leads.csv as input."

# Data Input Configuration
data_input:
  lead_source_type: csv
  csv_config:
    csv_file: "leads.csv"
  conversation_sql_file_bigquery: "bigquery.sql"

# LLM Configuration
llm_config:
  prompt_file: "prompt.txt"
  expected_llm_keys:
    lead_name:
      description: "Name of the lead extracted from conversation."
      type: str
    summary:
      description: "Estado + acción summary."
      type: str
    current_engagement_status:
      description: "Current engagement status of the lead."
      type: str
    follow_up_attempts:
      description: "Number of follow-up attempts."
      type: int
    next_action_code:
      description: "Code indicating next action to take."
      type: str
    next_action_context:
      description: "Context for next action."
      type: str
    suggested_message_es:
      description: "Suggested message in Spanish."
      type: str
  context_keys_from_python: []

# Python Processors
python_processors:
  - module: "lead_recovery.processors.metadata.MessageMetadataProcessor"
    params:
      max_message_length: 150
  - module: "lead_recovery.processors.handoff.HandoffProcessor"
    params: {}

output_columns:
  - cleaned_phone
  - lead_name
  - cache_status
  - summary
  - current_engagement_status
  - follow_up_attempts
  - last_message_sender
  - last_user_message_text
  - last_kuna_message_text
  - next_action_code
  - next_action_context
  - suggested_message_es
  - transfer_context_analysis
  - handoff_invitation_detected
  - handoff_response
  - handoff_finalized

# --- End of file --- 