# YAML Structure v2.2 - Post-Simulation/Handoff Analysis (Temporal Focus)
name: "handoffapp_to_bill"
output_columns:
  - name
  - last_name
  - email
  - cleaned_phone_number
  - customer_type
  - profiling_approval_date
  - cohort
  - converted_to_bill
  # YAML output keys (v2.2)
  - analysis_summary
  - inferred_stall_stage
  - primary_stall_reason_code
  - stall_trigger_event
  - last_lead_engagement
  - stall_context_detail
  - operational_insight_code
  - next_action_detail
  - contact_priority
dashboard_title: "HandoffApp‑to‑Bill Recovery"
summary_format: YAML
redshift_sql: handoffapp_to_bill_redshift.sql
bigquery_sql: handoffapp_to_bill_bigquery.sql
prompt_file: handoffapp_to_bill_prompt.txt
# List of keys the prompt is expected to generate in the YAML output (v2.2)
expected_yaml_keys:
  - analysis_summary
  - inferred_stall_stage
  - primary_stall_reason_code
  - stall_trigger_event
  - last_lead_engagement
  - stall_context_detail
  - operational_insight_code
  - next_action_detail
  - contact_priority
