# ========================================================================
# META CONFIGURATION FOR RECIPE: aprovado_handoff_cohort_abril
# ========================================================================

# --- Basic Recipe Identification ---
name: "aprovado_handoff_cohort_abril"
dashboard_title: "Recuperación Aprovado-Hand-Off Cohorte Abril"

# --- Data Source Configuration ---
redshift_sql: aprovado_handoff_cohort_abril_redshift.sql
bigquery_sql: aprovado_handoff_cohort_abril_bigquery.sql

# --- LLM Analysis Configuration ---
prompt_file: aprovado_handoff_cohort_abril_prompt_v12.txt
summary_format: YAML

# --- Output Structure Definition ---
# Defines the columns and their order in the final output CSV/DataFrame
output_columns:
  # Core lead info (adjust if needed)
  - folio_id
  - nombre
  - telefono
  - monto_preaprobado
  - profiling_approval_date

  # LLM Analysis Output (MUST match the order in the prompt's final YAML block)
  - summary
  - inferred_stall_stage
  - primary_stall_reason_code
  - timing_reasoning
  - prior_recovery_attempt_count
  - last_message_sender
  - human_transfer
  - last_user_message_before_transfer_trigger
  - last_user_message_text
  - last_kuna_message_text
  - next_action_code
  - next_action_context
  - suggested_message_es
  - transfer_context_analysis

# --- LLM Output Validation ---
# List of keys the Python script expects to find in the LLM's YAML output.
# MUST match the keys the prompt is instructed to generate.
expected_yaml_keys:
  - summary
  - inferred_stall_stage
  - primary_stall_reason_code
  - timing_reasoning
  - prior_recovery_attempt_count
  # - last_message_sender # Python-generated, should not be expected from LLM
  # - last_user_message_text # Python-generated, should not be expected from LLM
  # - last_kuna_message_text # Python-generated, should not be expected from LLM
  - next_action_code
  - next_action_context
  - suggested_message_es
  - transfer_context_analysis 