recipe_name: "marzo_cohorts_live"
version: "2.0"
description: "Analyzes marzo cohorts post-recovery attempt (May 8th onwards) for stall reason, recovery outcome, and next actions, using advanced Python flags."

data_input:
  lead_source_type: csv
  csv_config:
    csv_file: "leads.csv"
  conversation_sql_file_bigquery: "bigquery.sql"

llm_config:
  prompt_file: "prompt.txt"
  expected_llm_keys:
    summary:
      description: "A brief summary of the lead status."
      type: str
    inferred_stall_stage:
      description: "Stage where the lead stalled in the process."
      type: str
      enum_values:
        - "PRE_VALIDACION_PY"
        - "POST_VALIDACION_PY"
        - "HANDOFF_INVITACION_PENDIENTE_RESPUESTA"
        - "HANDOFF_DECLINADO_POR_USUARIO"
        - "HANDOFF_PROCESO_INICIADO_POR_USUARIO"
        - "HANDOFF_COMPLETADO"
        - "HANDOFF_ESTADO_DESCONOCIDO_PY"
    primary_stall_reason_code:
      description: "Primary reason code for the stall."
      type: str
      enum_values:
        - "GHOSTING_POST_RECUPERACION"
        - "AVANCES_EN_PROCESO"
        - "NO_INTERESADO_EXPLICITAMENTE"
        - "SOLICITO_NO_CONTACTAR"
        - "VEHICULO_ANTIGUO_KM"
        - "NO_PROPIETARIO"
        - "VIN_EXTRANJERO"
        - "ZONA_NO_CUBIERTA"
        - "ADEUDO_VEHICULAR"
        - "PROBLEMA_SEGUNDA_LLAVE"
        - "PROBLEMA_TERMINOS"
        - "ERROR_PROCESO_INTERNO"
        - "RECHAZADO_POR_KUNA"
        - "PRODUCTO_INCORRECTO_COMPRADOR"
        - "FINANCIAMIENTO_ACTIVO"
        - "ADEUDO_VEHICULAR_MULTAS"
        - "OTRO_PROCESO_DE_NEGOCIO"
        - "N/A"
        - "OTRO"
    prior_reactivation_attempt_count:
      description: "Count of prior reactivation attempts."
      type: int
    reactivation_status_assessment:
      description: "Assessment of reactivation status."
      type: str
      enum_values:
        - "NO_APLICA_AUN"
        - "PENDIENTE_PRIMERA_REACTIVACION"
        - "REACTIVACION_EN_CURSO_INTENTO_1_ENVIADO"
        - "REACTIVACION_EN_CURSO_INTENTO_2_ENVIADO"
        - "REACTIVACION_TARDIA_NECESITA_INTENTO_1"
        - "REACTIVACION_TARDIA_NECESITA_INTENTO_2"
        - "REACTIVACION_TARDIA_NECESITA_INTENTO_3"
        - "REACTIVACION_COMPLETA_3_INTENTOS_SIN_RESPUESTA"
        - "NO_APLICA_POR_CIERRE_O_ESPERA"
        - "NO_APLICA_FASE_RECUPERACION"
    transfer_context_analysis:
      description: "Analysis of transfer context."
      type: str
    next_action_code:
      description: "Code for the next action to take."
      type: str
      enum_values:
        - "CERRAR"
        - "ESPERAR"
        - "ESPERAR_CONTACTO_PROGRAMADO"
        - "IGNORAR"
        - "RECONTACTAR_INMEDIATO"
        - "ENVIAR_REACTIVACION"
        - "ESPERAR_FIN_REACTIVACION"
        - "ESPERAR_TEMPLATE_RECUPERACION"
        - "MANEJAR_OBJECION"
        - "LLAMAR_LEAD_NUNCA_RESPONDIO"
    next_action_context:
      description: "Context for the next action."
      type: str
    suggested_message_es:
      description: "Suggested message in Spanish for next contact."
      type: str
    thought_process:
      description: "Detailed thought process of analysis."
      type: str
    summary_what_went_wrong:
      description: "Summary of what went wrong with the lead."
      type: str
  context_keys_from_python: []

python_processors:
  - module: "lead_recovery.processors.temporal.TemporalProcessor"
    params:
      timezone: "America/Mexico_City"
  - module: "lead_recovery.processors.metadata.MessageMetadataProcessor"
    params:
      max_message_length: 150
  - module: "lead_recovery.processors.handoff.HandoffProcessor"
    params: {}
  - module: "lead_recovery.processors.human_transfer.HumanTransferProcessor"
    params: {}
  - module: "lead_recovery.processors.template.TemplateDetectionProcessor"
    params:
      template_type: "recovery"
  - module: "lead_recovery.processors.validation.ValidationProcessor"
    params: {}
  - module: "lead_recovery.processors.conversation_state.ConversationStateProcessor"
    params: {}

output_columns:
  - cleaned_phone
  - Email
  - Asset ID
  - Last Bureua Score
  - Max Loan
  - Nombre
  - Cohort
  - Control Group
  - Initial Step
  - Initial Step Date
  - Last Step
  - Last Step Date
  - Bill Date
  - handoff_reached
  - summary
  - inferred_stall_stage
  - primary_stall_reason_code
  - prior_reactivation_attempt_count
  - reactivation_status_assessment
  - transfer_context_analysis
  - next_action_code
  - next_action_context
  - suggested_message_es
  - thought_process
  - summary_what_went_wrong
  - conversation_state
  - pre_validacion_detected
  - handoff_invitation_detected
  - handoff_response
  - handoff_finalized
  - LAST_USER_MESSAGE_TIMESTAMP_TZ
  - LAST_MESSAGE_TIMESTAMP_TZ
  - HOURS_MINUTES_SINCE_LAST_USER_MESSAGE
  - HOURS_MINUTES_SINCE_LAST_MESSAGE
  - NO_USER_MESSAGES_EXIST
  - human_transfer
  - last_message_sender
  - last_user_message_text
  - last_kuna_message_text
  - recovery_template_detected
  - consecutive_recovery_templates_count
  - IS_WITHIN_REACTIVATION_WINDOW
  - IS_RECOVERY_PHASE_ELIGIBLE


