recipe_name: "marzo_cohorts"
version: "1.0"
description: "Analyzes marzo cohorts of leads to understand why they stalled."

data_input:
  lead_source_type: csv
  csv_config:
    csv_file: "leads.csv"
  conversation_sql_file_bigquery: "bigquery.sql"

llm_config:
  prompt_file: "prompt.txt"
  expected_llm_keys:
    primary_stall_reason_code:
      description: "Code representing primary reason the lead stalled."
      type: str
      enum_values:
        - "VEHICULO_ANTIGUO_KM"
        - "NO_PROPIETARIO"
        - "VIN_EXTRANJERO"
        - "ZONA_NO_CUBIERTA"
        - "ADEUDO_VEHICULAR"
        - "PROBLEMA_SEGUNDA_LLAVE"
        - "PROBLEMA_TERMINOS"
        - "GHOSTING"
        - "ERROR_PROCESO_INTERNO"
        - "RECHAZADO_POR_KUNA"
        - "PRODUCTO_INCORRECTO_COMPRADOR"
        - "OTHER_BUSINESS_PROCESS"
        - "FINANCIAMIENTO_ACTIVO"
        - "ADEUDO_VEHICULAR_MULTAS"
        - "OTRO_PROCESO_DE_NEGOCIO"
    summary_what_went_wrong:
      description: "Summary of what went wrong in the lead process."
      type: str
  context_keys_from_python: []

python_processors:
  - module: "lead_recovery.processors.metadata.MessageMetadataProcessor"
    params:
      max_message_length: 150
  - module: "lead_recovery.processors.handoff.HandoffProcessor"
    params: {}

output_columns:
  - cleaned_phone
  - primary_stall_reason_code
  - summary_what_went_wrong
