name: "Profiling Incomplete – No Profiling Completed"
output_columns:
  - lead_id
  - create_date
  - name
  - last_name
  - cleaned_phone
  - analysis_summary
  - stall_stage
  - stall_reason_code
  - last_agent_action
  - last_lead_response
  - stall_context
  - key_blocker
  - next_action
  - contact_priority
dashboard_title: "Profiling‑Incomplete Recovery"
summary_format: YAML
redshift_sql: redshift_profiling_incomplete.sql
bigquery_sql: bigquery_profiling_incomplete.sql
prompt_file: prompt_profiling_incomplete.txt
expected_yaml_keys:
  - analysis_summary
  - stall_stage
  - stall_reason_code
  - last_agent_action
  - last_lead_response
  - stall_context
  - key_blocker
  - next_action
  - contact_priority 